monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - generator
        - reader
        - http_client

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]
            
            generator:
                type: group
                members: [ generator_log, generator_logstash ]
                level: info
                channels: [ generator ]
            generator_log:
                type: stream
                path: "%kernel.logs_dir%/generator.%kernel.environment%.log.line"
                formatter: monolog.formatter.line
            generator_logstash:
                type: stream
                path: "%kernel.logs_dir%/generator.%kernel.environment%.log.logstash"
                formatter: 'monolog.formatter.logstash'

            
            reader:
                type: group
                members: [ reader_log, reader_logstash ]
                channels: [ reader ]
                level: info
            reader_log:
                type: stream
                path: "%kernel.logs_dir%/reader.%kernel.environment%.log.line"
                formatter: monolog.formatter.line
            reader_logstash:
                type: stream
                path: "%kernel.logs_dir%/reader.%kernel.environment%.log.logstash"
                formatter: 'monolog.formatter.logstash'

            http_client:
                type: group
                members: [ http_client_log, http_client_logstash ]
                channels: [ http_client ]
                level: info
            http_client_log:
                type: stream
                path: "%kernel.logs_dir%/http_client.%kernel.environment%.log.line"
                formatter: monolog.formatter.line
            http_client_logstash:
                type: stream
                path: "%kernel.logs_dir%/http_client.%kernel.environment%.log.logstash"
                formatter: 'monolog.formatter.logstash'

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            deprecation:
                type: stream
                channels: [ deprecation ]
                path: php://stderr
