build:
    environment:
        php:
            version: '8.2'

    dependencies:
        before:
            - cp docker/.env.dist .env
            - composer install --prefer-dist --no-interaction

    tests:
        override:
            - php vendor/bin/phpunit

filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

tools:
    php_code_sniffer: true
    php_mess_detector: true
    php_analyzer: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
    php_cs_fixer: true
