build:
    environment:
        php:
            version: '8.2'

    dependencies:
        before:
            - cp docker/.env.dist .env
            - cp .scrutinizer/phpunit.xml phpunit.xml
            - sudo apt-get update
            - sudo apt-get install -y poppler-utils
            - composer install --prefer-dist --no-interaction

filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

tools:
    php_code_sniffer: true
    php_mess_detector: true
    php_analyzer: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
    php_cs_fixer: true
